<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FitPass.Domain</RootNamespace>
    <AssemblyName>FitPass.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" />
  </ItemGroup>

</Project>
