//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitPass.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitPass.Application.Common.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not applicable for this request..
        /// </summary>
        public static string ActionIsApplicableForRequestType {
            get {
                return ResourceManager.GetString("ActionIsApplicableForRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have an ongoing request of this type..
        /// </summary>
        public static string AlreadyHaveOnGoingRequestOfThisType {
            get {
                return ResourceManager.GetString("AlreadyHaveOnGoingRequestOfThisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only update the gym&apos;s status to active or suspended..
        /// </summary>
        public static string AppAdminAllowedNewGymStatuses {
            get {
                return ResourceManager.GetString("AppAdminAllowedNewGymStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business rule violation..
        /// </summary>
        public static string BusinessRuleViolation {
            get {
                return ResourceManager.GetString("BusinessRuleViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pass is currently not available..
        /// </summary>
        public static string CannotBuyPassThatIsNotActive {
            get {
                return ResourceManager.GetString("CannotBuyPassThatIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot create a gym pass product for your gym because it is suspended..
        /// </summary>
        public static string CannotCreateGymPassProductForGymThatIsSuspended {
            get {
                return ResourceManager.GetString("CannotCreateGymPassProductForGymThatIsSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform action on user because they&apos;re in a different role..
        /// </summary>
        public static string CannotPerformActionOnRoleType {
            get {
                return ResourceManager.GetString("CannotPerformActionOnRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in use..
        /// </summary>
        public static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact info.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact info(s).
        /// </summary>
        public static string ContactInfosPluralOptional {
            get {
                return ResourceManager.GetString("ContactInfosPluralOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} currency is not supported.
        /// </summary>
        public static string CurrencyIsNotSupported {
            get {
                return ResourceManager.GetString("CurrencyIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum amount for {0} currency is: {1}.
        /// </summary>
        public static string CurrencyMinimumAmount {
            get {
                return ResourceManager.GetString("CurrencyMinimumAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days after expires.
        /// </summary>
        public static string DaysAfterExpires {
            get {
                return ResourceManager.GetString("DaysAfterExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set delay days if time interval is daily..
        /// </summary>
        public static string DelayDaysMustBeNullIfTimeIntervalisDaily {
            get {
                return ResourceManager.GetString("DelayDaysMustBeNullIfTimeIntervalisDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for signing up for {0}. Please confirm your email address by clicking the link below:
        ///
        ///Confirm my email: {1}.
        /// </summary>
        public static string EmailConfirmationEmailBody {
            get {
                return ResourceManager.GetString("EmailConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Confirm your email.
        /// </summary>
        public static string EmailConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("EmailConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards,
        /// {0}.
        /// </summary>
        public static string EmailFarewell {
            get {
                return ResourceManager.GetString("EmailFarewell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},.
        /// </summary>
        public static string EmailGreeting {
            get {
                return ResourceManager.GetString("EmailGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already confirmed..
        /// </summary>
        public static string EmailIsAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailIsAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email or phonenumber.
        /// </summary>
        public static string EmailOrPhoneNumber {
            get {
                return ResourceManager.GetString("EmailOrPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} external service is not available..
        /// </summary>
        public static string ExternalServiceUnavailable {
            get {
                return ResourceManager.GetString("ExternalServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fulfill your payment. The selected product not found. Please contact support..
        /// </summary>
        public static string FailedToFulfillGymPassProductPayment {
            get {
                return ResourceManager.GetString("FailedToFulfillGymPassProductPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gym.
        /// </summary>
        public static string Gym {
            get {
                return ResourceManager.GetString("Gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only your gym status to active or inactive..
        /// </summary>
        public static string GymAdminCanOnlySetGymStatusToActiveOrInactive {
            get {
                return ResourceManager.GetString("GymAdminCanOnlySetGymStatusToActiveOrInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current gym session has ended..
        /// </summary>
        public static string GymEmployeeEndedGymSession {
            get {
                return ResourceManager.GetString("GymEmployeeEndedGymSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You locker number has been updated to {0} by a gym employee..
        /// </summary>
        public static string GymEmployeeUpdatedGymPassUsageLockerNumber {
            get {
                return ResourceManager.GetString("GymEmployeeUpdatedGymPassUsageLockerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gym employee.
        /// </summary>
        public static string GymEmployment {
            get {
                return ResourceManager.GetString("GymEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not in active status..
        /// </summary>
        public static string GymIsNotActive {
            get {
                return ResourceManager.GetString("GymIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gym membership.
        /// </summary>
        public static string GymMembership {
            get {
                return ResourceManager.GetString("GymMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is banned from the gym..
        /// </summary>
        public static string GymMembershipIsBannedFromTheGym {
            get {
                return ResourceManager.GetString("GymMembershipIsBannedFromTheGym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass.
        /// </summary>
        public static string GymMembershipPass {
            get {
                return ResourceManager.GetString("GymMembershipPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gym membership has been banned..
        /// </summary>
        public static string GymMembershipStatusBannedEmailBody1 {
            get {
                return ResourceManager.GetString("GymMembershipStatusBannedEmailBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From today onwards, you will not be able to use the services of the {0} gym until the issue has been resolved. If you believe this is a mistake or you need further information, please contact the gym..
        /// </summary>
        public static string GymMembershipStatusBannedEmailBody2 {
            get {
                return ResourceManager.GetString("GymMembershipStatusBannedEmailBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been banned from {0}.
        /// </summary>
        public static string GymMembershipStatusBannedEmailSubject {
            get {
                return ResourceManager.GetString("GymMembershipStatusBannedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gym membership is active again!.
        /// </summary>
        public static string GymMembershipStatusUnbannedEmailBody1 {
            get {
                return ResourceManager.GetString("GymMembershipStatusUnbannedEmailBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From today onwards, you can once again make full use of the services of the {0} gym.
        ///We look forward to welcoming you back!.
        /// </summary>
        public static string GymMembershipStatusUnbannedEmailBody2 {
            get {
                return ResourceManager.GetString("GymMembershipStatusUnbannedEmailBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gym membership ban has been lifted from {0}.
        /// </summary>
        public static string GymMembershipStatusUnbannedEmailSubject {
            get {
                return ResourceManager.GetString("GymMembershipStatusUnbannedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gym pass product.
        /// </summary>
        public static string GymPassProduct {
            get {
                return ResourceManager.GetString("GymPassProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were recently unable to fulfill your payment to {0}. Please check that your payment was correct. If it was open a ticket with and reference the following receipt id: {1}.
        /// </summary>
        public static string GymPassProductPurchaseFulfillmentFailedEmailBody {
            get {
                return ResourceManager.GetString("GymPassProductPurchaseFulfillmentFailedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your recent payment could not be completed.
        /// </summary>
        public static string GymPassProductPurchaseFulfillmentFailedEmailSubject {
            get {
                return ResourceManager.GetString("GymPassProductPurchaseFulfillmentFailedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass usage.
        /// </summary>
        public static string GymPassUsage {
            get {
                return ResourceManager.GetString("GymPassUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gym has been reactivated by an App Administrator with the following rationale: {0}.
        /// </summary>
        public static string GymReactivatedByAppAdmin {
            get {
                return ResourceManager.GetString("GymReactivatedByAppAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gym has been reactivated by an application administrator. To avoid potential misunderstandings going forward, we kindly ask that you review our guidelines. Please note that the following rationale was previously given with the suspension: {0}.
        /// </summary>
        public static string GymReactivatedByAppAdminEmailBody {
            get {
                return ResourceManager.GetString("GymReactivatedByAppAdminEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gym has been reactivated..
        /// </summary>
        public static string GymReactivatedByAppAdminEmailSubject {
            get {
                return ResourceManager.GetString("GymReactivatedByAppAdminEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gym status.
        /// </summary>
        public static string GymStatus {
            get {
                return ResourceManager.GetString("GymStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gym has been suspended by an App Administrator with the following rationale: {0}.
        /// </summary>
        public static string GymSuspendedByAppAdmin {
            get {
                return ResourceManager.GetString("GymSuspendedByAppAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gym has been suspended by an application administrator. To avoid potential misunderstandings going forward, we kindly ask that you review our guidelines. The following rationale was given with the suspension: {0}.
        /// </summary>
        public static string GymSuspendedByAppAdminEmailBody {
            get {
                return ResourceManager.GetString("GymSuspendedByAppAdminEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gym has been suspended..
        /// </summary>
        public static string GymSuspendedByAppAdminEmailSubject {
            get {
                return ResourceManager.GetString("GymSuspendedByAppAdminEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request type..
        /// </summary>
        public static string InvalidRequestType {
            get {
                return ResourceManager.GetString("InvalidRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active status.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given language is not supported. Supported languages: {0}.
        /// </summary>
        public static string LanguageIsNotSupported {
            get {
                return ResourceManager.GetString("LanguageIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locker number.
        /// </summary>
        public static string LockerNumber {
            get {
                return ResourceManager.GetString("LockerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly anchor cannot be empty if the time interval is monthly..
        /// </summary>
        public static string MonthlyAnchorCannotBeEmptyIfTheTimeIntervalIsMonthly {
            get {
                return ResourceManager.GetString("MonthlyAnchorCannotBeEmptyIfTheTimeIntervalIsMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi use pass type must have at least two uses..
        /// </summary>
        public static string MultiUsePassTypeMustHaveAtLeastTwoUses {
            get {
                return ResourceManager.GetString("MultiUsePassTypeMustHaveAtLeastTwoUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be the same as old..
        /// </summary>
        public static string NewPasswordCannotBeSameAsOld {
            get {
                return ResourceManager.GetString("NewPasswordCannotBeSameAsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new {0}.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change the locker number once the gym session ended..
        /// </summary>
        public static string NoChangingLockerNumberAfterGymSessionEnded {
            get {
                return ResourceManager.GetString("NoChangingLockerNumberAfterGymSessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass has no uses left..
        /// </summary>
        public static string PassHasNoUsesLeft {
            get {
                return ResourceManager.GetString("PassHasNoUsesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass is expired..
        /// </summary>
        public static string PassIsExpired {
            get {
                return ResourceManager.GetString("PassIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pass is for another gym..
        /// </summary>
        public static string PassIsForAnotherGym {
            get {
                return ResourceManager.GetString("PassIsForAnotherGym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass does not belong to user..
        /// </summary>
        public static string PassNotBelongsToUser {
            get {
                return ResourceManager.GetString("PassNotBelongsToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lower case character..
        /// </summary>
        public static string PasswordAtLeastOneLowerCase {
            get {
                return ResourceManager.GetString("PasswordAtLeastOneLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number..
        /// </summary>
        public static string PasswordAtLeastOneNumber {
            get {
                return ResourceManager.GetString("PasswordAtLeastOneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character..
        /// </summary>
        public static string PasswordAtLeastOneSpecial {
            get {
                return ResourceManager.GetString("PasswordAtLeastOneSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one upper case character..
        /// </summary>
        public static string PasswordAtLeastOneUpperCase {
            get {
                return ResourceManager.GetString("PasswordAtLeastOneUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be longer than {0} characters..
        /// </summary>
        public static string PasswordMaximumLength {
            get {
                return ResourceManager.GetString("PasswordMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters..
        /// </summary>
        public static string PasswordMinimumLength {
            get {
                return ResourceManager.GetString("PasswordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received a request to reset the password for your account. Click the link below to set a new password: {0}.
        /// </summary>
        public static string PasswordResetEmailBody {
            get {
                return ResourceManager.GetString("PasswordResetEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Request.
        /// </summary>
        public static string PasswordResetEmailSubject {
            get {
                return ResourceManager.GetString("PasswordResetEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match..
        /// </summary>
        public static string PasswordsMustMatch {
            get {
                return ResourceManager.GetString("PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload free requests cannot have type of gym creation or gym admin promotion..
        /// </summary>
        public static string PayloadFreeRequestTypeRules {
            get {
                return ResourceManager.GetString("PayloadFreeRequestTypeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripe Connected account.
        /// </summary>
        public static string PaymentProviderConnectedAccount {
            get {
                return ResourceManager.GetString("PaymentProviderConnectedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment required..
        /// </summary>
        public static string PaymentRequired {
            get {
                return ResourceManager.GetString("PaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string PropertyIsRequired {
            get {
                return ResourceManager.GetString("PropertyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be longer than {1} characters..
        /// </summary>
        public static string PropertyMaxLength {
            get {
                return ResourceManager.GetString("PropertyMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters..
        /// </summary>
        public static string PropertyMinLength {
            get {
                return ResourceManager.GetString("PropertyMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string PropertyOf {
            get {
                return ResourceManager.GetString("PropertyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rationale.
        /// </summary>
        public static string Rationale {
            get {
                return ResourceManager.GetString("Rationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error while handling request..
        /// </summary>
        public static string RequestHandlingError {
            get {
                return ResourceManager.GetString("RequestHandlingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is not open..
        /// </summary>
        public static string RequestIsNotOpen {
            get {
                return ResourceManager.GetString("RequestIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires account activation..
        /// </summary>
        public static string RequiresAccountActivation {
            get {
                return ResourceManager.GetString("RequiresAccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires email confirmation..
        /// </summary>
        public static string RequiresEmailConfirmation {
            get {
                return ResourceManager.GetString("RequiresEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first create your Stripe account..
        /// </summary>
        public static string RequiresStripeAccount {
            get {
                return ResourceManager.GetString("RequiresStripeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string ResourceAlreadyExists {
            get {
                return ResourceManager.GetString("ResourceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single use type pass can only have one total use..
        /// </summary>
        public static string SingleUsePassCanOnlyHaveOneTotalUse {
            get {
                return ResourceManager.GetString("SingleUsePassCanOnlyHaveOneTotalUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful purchase!.
        /// </summary>
        public static string SuccessfulPurchase {
            get {
                return ResourceManager.GetString("SuccessfulPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment profile.
        /// </summary>
        public static string TenantPaymentProfile {
            get {
                return ResourceManager.GetString("TenantPaymentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time interval.
        /// </summary>
        public static string TimeInterval {
            get {
                return ResourceManager.GetString("TimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total uses.
        /// </summary>
        public static string TotalUses {
            get {
                return ResourceManager.GetString("TotalUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited pass types&apos; days after expires must be at least one..
        /// </summary>
        public static string UnlimitedPassDaysAfterExpiresAtLeastOne {
            get {
                return ResourceManager.GetString("UnlimitedPassDaysAfterExpiresAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited pass type cannot have uses..
        /// </summary>
        public static string UnlimitedPassTypesCannotHaveUses {
            get {
                return ResourceManager.GetString("UnlimitedPassTypesCannotHaveUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use based pass type cannot have expiration time..
        /// </summary>
        public static string UseBasedPassTypeCannotHaveExpirationTime {
            get {
                return ResourceManager.GetString("UseBasedPassTypeCannotHaveExpirationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use based pass type must have at least one use..
        /// </summary>
        public static string UseBasedPassTypeMustHaveOneUse {
            get {
                return ResourceManager.GetString("UseBasedPassTypeMustHaveOneUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has password set..
        /// </summary>
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has an ongoing gym session..
        /// </summary>
        public static string UserHasOngoingGymSession {
            get {
                return ResourceManager.GetString("UserHasOngoingGymSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set a password..
        /// </summary>
        public static string UserHasToSetAPassword {
            get {
                return ResourceManager.GetString("UserHasToSetAPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        public static string ValueIsInvalid {
            get {
                return ResourceManager.GetString("ValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly anchor cannot be empty is the time interval is weekly..
        /// </summary>
        public static string WeeklyAnchorCannotBeNullIfTimeIntervalIsWeekly {
            get {
                return ResourceManager.GetString("WeeklyAnchorCannotBeNullIfTimeIntervalIsWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created successfully and you are all set to start using {0}. With your account, you can discover gyms, manage your memberships, and track your visits easily. Please activate your account here: {1}.
        /// </summary>
        public static string WelcomeEmailBody {
            get {
                return ResourceManager.GetString("WelcomeEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To {0}!.
        /// </summary>
        public static string WelcomeEmailSubject {
            get {
                return ResourceManager.GetString("WelcomeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gym is suspended..
        /// </summary>
        public static string YourGymIsSuspended {
            get {
                return ResourceManager.GetString("YourGymIsSuspended", resourceCulture);
            }
        }
    }
}
